// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {macroWHighlight} from "./macroW.highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UQYQPOOOhQPO'#CjO!VQPO'#CoO![QPO'#CpOOQO'#Ch'#ChOOQO'#Cc'#CcQYQPOOO!gQPO,59UOOQO'#Cq'#CqOOQO'#Cd'#CdO#UQPO,59ZO#sQPO,59[OOQO-E6a-E6aOOQO-E6b-E6bO#xQPO1G.uO$gQPO1G.vO$uQPO7+$bOYQPO<<G|OOQOAN=hAN=hOOQO7+$b7+$bO$gQPO1G.vO%ZQPO,59[O![QPO'#CpP$gQPO<<G|",
  stateData: "%h~OZOSPOS~ORQOSRO]SO_PO~O`WOaWObWOR^XS^XX^X]^X_^XU^X~OaYO~O`WOaWObWO~O`WOaWObWOR^aS^aX^a]^a_^aU^a~O`WOaWObWORcaScaXca]ca_caUca~OT_O~O`WOaWObWORciSciXci]ci_ciUci~ORQOSfO]SO_PO~OUaORdqSdqXdq]dq_dq~OTdO~OSTU_]a_~",
  goto: "!kfPPPPPPPgmPPPwP!VPPPP!V!V!_QUOR[UQVPS]V^R^YSTOUQ`_SbagRcd]SOU_adgWXPVY^QZRRef",
  nodeNames: "⚠ LineComment Program . IF THEN ELSE",
  maxTerm: 21,
  propSources: [macroWHighlight],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "5v~RrX^#]pq#]!O!P$Q!P!Q$V!Q![$t!b!c$|!c!g%h!g!h&R!h!k%h!k!l(Z!l!v%h!v!w)]!w!}%h#T#W%h#W#X+e#X#`%h#`#a._#a#b.v#b#c%h#c#d/|#d#e1S#e#g%h#g#h2}#h#k%h#k#l5U#l#o%h#y#z#]$f$g#]#BY#BZ#]$IS$I_#]$I|$JO#]$JT$JU#]$KV$KW#]&FU&FV#]~#bYZ~X^#]pq#]#y#z#]$f$g#]#BY#BZ#]$IS$I_#]$I|$JO#]$JT$JU#]$KV$KW#]&FU&FV#]~$VOR~~$YP!P!Q$]~$bSP~OY$]Z;'S$];'S;=`$n<%lO$]~$qP;=`<%l$]~$yP`~!Q![$t~%PQ!c!}%V#T#o%V~%[Sb~!Q![%V!c!}%V#R#S%V#T#o%V~%mTa~!Q![%h![!]%|!c!}%h#R#S%h#T#o%h~&RO]~~&WVa~!Q![%h![!]%|!c!n%h!n!o&m!o!}%h#R#S%h#T#o%h~&rVa~!Q![%h![!]%|!c!u%h!u!v'X!v!}%h#R#S%h#T#o%h~'^Va~!Q![%h![!]%|!c!g%h!g!h's!h!}%h#R#S%h#T#o%h~'zTU~a~!Q![%h![!]%|!c!}%h#R#S%h#T#o%h~(`Va~!Q![%h![!]%|!c!h%h!h!i(u!i!}%h#R#S%h#T#o%h~(|TS~a~!Q![%h![!]%|!c!}%h#R#S%h#T#o%h~)bVa~!Q![%h![!]%|!c!j%h!j!k)w!k!}%h#R#S%h#T#o%h~)|Va~!Q![%h![!]%|!c!g%h!g!h*c!h!}%h#R#S%h#T#o%h~*hVa~!Q![%h![!]%|!c!p%h!p!q*}!q!}%h#R#S%h#T#o%h~+UTT~a~!Q![%h![!]%|!c!}%h#R#S%h#T#o%h~+jXa~!Q![%h![!]%|!c!}%h#R#S%h#T#b%h#b#c,V#c#d-X#d#n%h#n#o-s~,[Va~!Q![%h![!]%|!c!}%h#R#S%h#T#g%h#g#h,q#h#o%h~,xT_~a~!Q![%h![!]%|!c!}%h#R#S%h#T#o%h~-^Va~!Q![%h![!]%|!c!}%h#R#S%h#T#W%h#W#X,q#X#o%h~-xVa~!Q![%h![!]%|!c!}%h#R#S%h#T#]%h#]#^,q#^#o%h~.dUa~!Q![%h![!]%|!c!}%h#R#S%h#T#U-X#U#o%h~.{Va~!Q![%h![!]%|!c!}%h#R#S%h#T#b%h#b#c/b#c#o%h~/gVa~!Q![%h![!]%|!c!}%h#R#S%h#T#c%h#c#d,q#d#o%h~0RVa~!Q![%h![!]%|!c!}%h#R#S%h#T#W%h#W#X0h#X#o%h~0mVa~!Q![%h![!]%|!c!}%h#R#S%h#T#X%h#X#Y,q#Y#o%h~1XYa~!Q![%h![!]%|!c!}%h#R#S%h#T#c%h#c#d1w#d#k%h#k#l2c#l#n%h#n#o,V~1|Va~!Q![%h![!]%|!c!}%h#R#S%h#T#U%h#U#V,q#V#o%h~2hVa~!Q![%h![!]%|!c!}%h#R#S%h#T#f%h#f#g,q#g#o%h~3SZa~!Q![%h![!]%|!c!}%h#R#S%h#T#W%h#W#X3u#X#c%h#c#d4a#d#h%h#h#i3u#i#o%h~3zVa~!Q![%h![!]%|!c!}%h#R#S%h#T#d%h#d#e,q#e#o%h~4fYa~!Q![%h![!]%|!c!}%h#R#S%h#T#U%h#U#V,q#V#a%h#a#b,q#b#n%h#n#o,q~5ZXa~!Q![%h![!]%|!c!}%h#R#S%h#T#d%h#d#e2c#e#m%h#m#n3u#n#o%h",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 200
})
