// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {macroWHighlight} from "./macroW.highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UQYQPOOOhQPO'#CjO!VQPO'#CoO![QPO'#CpOOQO'#Ch'#ChOOQO'#Cc'#CcQYQPOOO!gQPO,59UOOQO'#Cq'#CqOOQO'#Cd'#CdO#UQPO,59ZO#sQPO,59[OOQO-E6a-E6aOOQO-E6b-E6bO#xQPO1G.uO$gQPO1G.vO$uQPO7+$bOYQPO<<G|OOQOAN=hAN=hOOQO7+$b7+$bO$gQPO1G.vO%ZQPO,59[O![QPO'#CpP$gQPO<<G|",
  stateData: "%h~OZOSPOS~ORQOSRO]SO_PO~O`WOaWObWOR^XS^XX^X]^X_^XU^X~OaYO~O`WOaWObWO~O`WOaWObWOR^aS^aX^a]^a_^aU^a~O`WOaWObWORcaScaXca]ca_caUca~OT_O~O`WOaWObWORciSciXci]ci_ciUci~ORQOSfO]SO_PO~OUaORdqSdqXdq]dq_dq~OTdO~OSTU_]a_~",
  goto: "!kfPPPPPPPgmPPPwP!VPPPP!V!V!_QUOR[UQVPS]V^R^YSTOUQ`_SbagRcd]SOU_adgWXPVY^QZRRef",
  nodeNames: "⚠ LineComment Program . IF THEN ELSE",
  maxTerm: 21,
  propSources: [macroWHighlight],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "+V~RfX^!gpq!g!O!P#[!P!Q#a!Q![$O!b!c$W!c!g$r!g!h%_!h!k$r!k!l'o!l!v$r!v!w(u!w!}$r#T#o$r#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~!lYZ~X^!gpq!g#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~#aOR~~#dP!P!Q#g~#lSP~OY#gZ;'S#g;'S;=`#x<%lO#g~#{P;=`<%l#g~$TP`~!Q![$O~$ZQ!c!}$a#T#o$a~$fSb~!Q![$a!c!}$a#R#S$a#T#o$a~$yT_~a~!Q![$r![!]%Y!c!}$r#R#S$r#T#o$r~%_O]~~%fV_~a~!Q![$r![!]%Y!c!n$r!n!o%{!o!}$r#R#S$r#T#o$r~&SV_~a~!Q![$r![!]%Y!c!u$r!u!v&i!v!}$r#R#S$r#T#o$r~&pV_~a~!Q![$r![!]%Y!c!g$r!g!h'V!h!}$r#R#S$r#T#o$r~'`TU~_~a~!Q![$r![!]%Y!c!}$r#R#S$r#T#o$r~'vV_~a~!Q![$r![!]%Y!c!h$r!h!i(]!i!}$r#R#S$r#T#o$r~(fTS~_~a~!Q![$r![!]%Y!c!}$r#R#S$r#T#o$r~(|V_~a~!Q![$r![!]%Y!c!j$r!j!k)c!k!}$r#R#S$r#T#o$r~)jV_~a~!Q![$r![!]%Y!c!g$r!g!h*P!h!}$r#R#S$r#T#o$r~*WV_~a~!Q![$r![!]%Y!c!p$r!p!q*m!q!}$r#R#S$r#T#o$r~*vTT~_~a~!Q![$r![!]%Y!c!}$r#R#S$r#T#o$r",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 200
})
