// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
import { maszynaWHighlight } from './maszynaW.highlight.js';
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "$OQYQPOOOhQPO'#ClOOQO'#Cp'#CpOmQPO'#CpOOQO'#Ck'#CkQYQPOOOrQPO'#CoOOQO'#Ce'#CeO!QQPO'#CeO!VQPO,59WOOQO,59[,59[OOQO-E6c-E6cO![QPO,59ZO!jQPO'#CfOOQO'#Cf'#CfOOQO,59P,59PO!oQPO1G.rOOQO-E6d-E6dOOQO,59Q,59QOOQO'#Cm'#CmO!wQPO7+$^O!oQPO<<GxOOQOAN=dAN=d",
  stateData: '#W~O]OSPOS~ORPOUUO^VObRO~OSXO~OUUO~OU^OV]O^cXWcX~O^_O~OT`O~OU^OV]O^caWca~OUbO~OUUObcO~OWeO^`q~ORTWUbW~',
  goto: '!]ePPPPPPPPPflPPPPrvzP!QvQTORZTQ[URa[TWOTTSOTQd`RfeSQOTQYRTc`e',
  nodeNames: '⚠ LineComment Program IF Flag THEN Keyword , ELSE',
  maxTerm: 20,
  propSources: [maszynaWHighlight],
  skippedNodes: [0, 1],
  repeatNodeCount: 2,
  tokenData:
    ",Y~RnX^#Ppq#P|}#t!P!Q#y!]!^$h!b!c$m!g!h%X!k!l%p!p!q%{!v!w&Q!|!}%{#T#U&i#V#W&t#W#X'W#]#^(V#`#a(b#a#b(n#b#c(z#c#d)W#d#e)d#g#h*]#k#l*x#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#UY]~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#yOV~~#|P!P!Q$P~$USP~OY$PZ;'S$P;'S;=`$b<%lO$P~$eP;=`<%l$P~$mO^~~$pQ!c!}$v#T#o$v~${Sb~!Q![$v!c!}$v#R#S$v#T#o$v~%[P!n!o%_~%bP!u!v%e~%hP!g!h%k~%pOW~~%sP!h!i%v~%{OR~~&QOS~~&TP!j!k&W~&ZP!g!h&^~&aP!p!q&d~&iOT~~&lP#g#h&o~&tOU~~&wP#n#o&z~&}P#m#n'Q~'TP#h#i&o~'ZS#T#U'g#`#a&o#c#d'm#n#o's~'jP#_#`&o~'pP#W#X&o~'vP#]#^'y~'|P#X#Y(P~(SP#`#a&o~([QU~#T#U'g#`#a&o~(eP#i#j(h~(kP#U#V&o~(qP#b#c(t~(wP#c#d&o~(}P#X#Y)Q~)TP#Z#[&o~)ZP#W#X)^~)aP#X#Y&o~)gQ#]#^)m#f#g)y~)pP#g#h)s~)vP#n#o&o~)|P#n#o*P~*SP#X#Y*V~*YP#d#e&o~*`R#T#U&o#[#]*i#h#i*r~*lQ#`#a&o#f#g&o~*uP#c#d*V~*{Q#X#Y+R#m#n+s~+UT#T#U+e#]#^&o#^#_+m#`#a&o#g#h&o~+jPU~#_#`&o~+pP#T#U&o~+vR#T#U,P#`#a&o#g#h&o~,SQ#W#X&o#_#`&o",
  tokenizers: [0],
  topRules: { Program: [0, 2] },
  tokenPrec: 93,
});
