import type { Machine, MachineActions, MicroActions } from './Types/Machine';
import { executionActions } from './Actions/ExecutionActions';
import { webSocketActions } from './Actions/WebSocketActions';
import { configurationActions } from './Actions/ConfigurationActions';
import { presentationActions } from './Actions/PresentationActions';

/** Composes machine operations in their original order; the store binds every method to the machine. */
export const machineMethods: Omit<MachineActions, keyof MicroActions> & ThisType<Machine> = {
  showToast: presentationActions.showToast,
  getMaxValueForRegister: configurationActions.getMaxValueForRegister,
  toggleBreakpoint: executionActions.toggleBreakpoint,
  _shouldPauseOnBreakpoint: executionActions._shouldPauseOnBreakpoint,
  reconnectWS: webSocketActions.reconnectWS,
  holdBus: executionActions.holdBus,
  getDefaultExtras: configurationActions.getDefaultExtras,
  mergeExtras: configurationActions.mergeExtras,
  to8: executionActions.to8,
  toWord: executionActions.toWord,
  wordMask: executionActions.wordMask,
  addrMask: executionActions.addrMask,
  stackPush: executionActions.stackPush,
  stackPop: executionActions.stackPop,
  handleProgramSectionCompile: executionActions.handleProgramSectionCompile,
  handleAsmAutoReset: executionActions.handleAsmAutoReset,
  applyInitMemory: executionActions.applyInitMemory,
  initWebsocket: webSocketActions.initWebsocket,
  handleRemoteToggleLocalWebSocket: webSocketActions.handleRemoteToggleLocalWebSocket,
  handleRemoteToggleESPWebSocket: webSocketActions.handleRemoteToggleESPWebSocket,
  checkConflict: executionActions.checkConflict,
  handleSignalToggle: executionActions.handleSignalToggle,
  sendSignalToESP: webSocketActions.sendSignalToESP,
  sendPartialData: webSocketActions.sendPartialData,
  sendMemUpdate: webSocketActions.sendMemUpdate,
  sendFullDataToESP: webSocketActions.sendFullDataToESP,
  sendColorToESP: webSocketActions.sendColorToESP,
  handleRemoteMemUpdate: webSocketActions.handleRemoteMemUpdate,
  syncDocumentLanguage: configurationActions.syncDocumentLanguage,
  addLog: presentationActions.addLog,
  translateLogMessage: presentationActions.translateLogMessage,
  formatNumber: presentationActions.formatNumber,
  decToCommand: presentationActions.decToCommand,
  decToArgument: presentationActions.decToArgument,
  resizeMemory: configurationActions.resizeMemory,
  manualModeCheck: configurationActions.manualModeCheck,
  manualModeUncheck: configurationActions.manualModeUncheck,
  manualModeChanged: configurationActions.manualModeChanged,
  closePopups: presentationActions.closePopups,
  openLabDialog: presentationActions.openLabDialog,
  closeLabDialog: presentationActions.closeLabDialog,
  selectLab: presentationActions.selectLab,
  loadSelectedLab: executionActions.loadSelectedLab,
  compileCode: executionActions.compileCode,
  uncompileCode: executionActions.uncompileCode,
  handleInterrupt: executionActions.handleInterrupt,
  executeLine: executionActions.executeLine,
  _refreshHighlight: executionActions._refreshHighlight,
  getResolvedPhase: executionActions.getResolvedPhase,
  evaluateFlag: executionActions.evaluateFlag,
  stopRun: executionActions.stopRun,
  runCode: executionActions.runCode,
  _stopRun: executionActions._stopRun,
  runToEndFast: executionActions.runToEndFast,
  resetValues: executionActions.resetValues,
  restoreDefaults: configurationActions.restoreDefaults,
  openCommandList: presentationActions.openCommandList,
  toggleConsole: presentationActions.toggleConsole,
  closeConsole: presentationActions.closeConsole,
  clearConsole: presentationActions.clearConsole,
  handleKeyPress: presentationActions.handleKeyPress,
  clearActiveTimeouts: executionActions.clearActiveTimeouts,
  testEnhancedConsole: presentationActions.testEnhancedConsole,
};
